name = "aiken-lang/advance-nft-marketplacxe"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/advance-nft-marketplacxe'"

[repository]
user = "aiken-lang"
project = "advance-nft-marketplacxe"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config]
